### ISSUE TITLE
Open local pdb files in LiteMol

### ISSUE THREAD

**Issue by Birch78** [dsehnal/LiteMol#28]
I am a complete novice in LiteMol so sorry for this "stupid" question. I want a LiteMol viewer on my hompage and used the example here (http://embed.plnkr.co/looflQ9owiGW0m9bh0fF/). But I have one major issue:
1) No molecule is loaded in the viewer, and more importantly 
2) If i have my pdb file located in a folder how do I load this specific pdb file in the viewer?

Thanks in advance.

My code is:
```
<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="style.css">
    
    <!-- Complied & minified library css -->
    <link rel="stylesheet" href="//www.ebi.ac.uk/pdbe/pdb-component-library/v1.0/css/pdb.component.library.min-1.0.0.css" />

    <!-- Dependencey scripts (these can be skipped if already included in page) -->
    <script src="//www.ebi.ac.uk/pdbe/pdb-component-library/libs/d3.min.js"></script>
    <script src="//www.ebi.ac.uk/pdbe/pdb-component-library/libs/angular.1.4.7.min.js"></script>

    <!-- Complied & minified library JS -->
    <script src="//www.ebi.ac.uk/pdbe/pdb-component-library/v1.0/js/pdb.component.library.min-1.0.0.js"></script>
    
    <script src="script.js"></script>
  </head>

  <body>
    <h3>LiteMol Component Demo</h3>
    
    <div class="view3d">
      <pdb-lite-mol id="litemol_1cbs" pdb-id="'1aqd'" hide-controls="true"></pdb-lite-mol>
    </div>
    
  </body>

</html>
```

**Comment by mandarsd** [comment]
Hi

Could you please check and share if there are any console error logs? as the example you are referring to is working fine I couldn't do any debugging on my side. 

Just for your information, the LiteMol viewer implementation you are using is an Angular js component wrapper for LiteMol.  You'll need a Local web server in order to get the example working on your local browser. Here is how you can set up a node js simple http server on your machine - 
[http://jasonwatmore.com/post/2016/06/22/nodejs-setup-simple-http-server-local-web-server](http-server)

To view your own files in the LiteMol component, you'll have to host them and provide the file path by setting the 'source-url' attribute. 
You can find the information about all the available attributes on the PDB Component Library documentation page [https://www.ebi.ac.uk/pdbe/pdb-component-library/doc.html#a_LiteMol](here)

**Comment by Birch78** [comment]
Hi Mandarsd

Thanks a lot. I will try to follow your suggestion later tonight. However, non of your links are working... But maybe you can help me with some guidance. I ONLY want er viewer without any properties besides the ability to rotate the molecule, and view the pdf file located in a folder. Could you maybe show me a simple code for this?

Thanks a lot

**Comment by mandarsd** [comment]
Sorry I have fixed the links

**Comment by Birch78** [comment]
So by the "pdf file located in a folder" I mean the folder is uploaded with the rest of my website folders.

**Comment by Birch78** [comment]
Hi Mandarsd

I got the LiteMol to load the pdb file, but for some reason I will not show the icons in the top of the window (Here is the site: http://www.epsdatabase.com/litemol_test2.html). Do you know why this is?

Could you PLEASE show an example on how to code the file path by setting the 'source-url' attribute. For instance if I have the pdb files in a "PDBfolder" uploaded on my website files?

THANKS A LOT

**Comment by Birch78** [comment]
Hi Mandarsd

I got everything working fine, except the local pdb file. I have the pdb in a folder uploaded together with the rest of my website files. Could you PLEASE show me how I provide the file path by setting the 'source-url' attribute?

THANKS A LOT

**Comment by MandarSDeshpande** [comment]
Hi,

Here is the working demo to render pdb using 'source-url' attribute

[source-url demo](https://embed.plnkr.co/zF2KS6GgX8fi6j2FXX80/)

Regarding the icons, I see you copied the library css and js files. css file has icon-fonts included and those files are missing on your local :)
You can use the pdbe css url like cdn in your app, which should resolve the problem or download font files from [here](https://github.com/mandarsd/pdb-lite-mol/tree/master/assets/fonts)

**Comment by mandarsd** [comment]
Here is the working demo to render pdb using 'source-url' attribute

[source-url demo](https://embed.plnkr.co/zF2KS6GgX8fi6j2FXX80/)

Regarding the icons, I see you copied the library css and js files. css file has icon-fonts included and those files are missing on your local :)
You can use the pdbe css url like cdn in your app, which should resolve the problem or download font files from [here](https://github.com/mandarsd/pdb-lite-mol/tree/master/assets/fonts)

**Comment by Birch78** [comment]
I am so sorry that I am such a BEGINNER. So how do i link to a homemade pdb file located in for instance the css library?

Thank you so much for all your help

**Comment by mandarsd** [comment]
Just add the complete path of your pdb file in the source-url attribute

For example : source-url='https://www.your_website.com/SOME_FOLDER/PDB_FILENAME"

**Comment by Birch78** [comment]
Hi again

Thanks a lot for helping me out. I am still unable to make this work. I am using: source-url="https://www.epsdatabase.com/litemol_js/1dv9.pdb" but without luck...

**Comment by ye1002551506** [comment]
If you want to run a local pdb file, you should open a server, such as http-server, after setting up the server, set source-url = "http://localhost/.../a.pdb" Run it. The question about setting the source-url can be seen in the Hide attribute / parameter details at https://www.ebi.ac.uk/pdbe/pdb-component-library/doc.html#a_LiteMol. good luck

**Comment by dsehnal** [comment]
Hi,

regarding the URL https://www.epsdatabase.com/litemol_js/1dv9.pdb , there are these potential problems which prevent the access to this file:

- your HTTPS does not work as it should (probably a bad certificate).
- the server does not support cross origin requests (CORS, i.e. lacks the ``Access-Control-Allow-Origin: *`` header). This means that if you access the data from a different domain, the JavaScript is unable to download the file.

David
